apiVersion: v1
kind: Secret
metadata:
  name: mariadb-root-password
type: Opaque
stringData:
  password: {{ .Values.db.password | default "OpenMRS123" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-user-password
type: Opaque
stringData:
  password: {{ .Values.db.password | default "OpenMRS123" | quote }}